export const MODULE_REGISTRY_DATA = [
  {
    id: 'todo',
    displayName: 'To do',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="todo.html"]',
    handlerName: 'navigateTodoPage',
    ownerPath: 'src/modules/todo/controller.ts',
    iconElementId: 'todo-icon',
    routeHref: 'todo.html',
    dataModule: 'todo',
  },
  {
    id: 'being',
    displayName: 'Being',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="being.html"]',
    handlerName: 'navigateBeingPage',
    ownerPath: 'src/modules/being/controller.ts',
    iconElementId: 'being-icon',
    routeHref: 'being.html',
    dataModule: 'being',
  },
  {
    id: 'tennis',
    displayName: 'Tennis',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="tennis.html"]',
    handlerName: 'navigateTennisPage',
    ownerPath: 'src/modules/tennis/controller.ts',
    iconElementId: 'tennis-icon',
    routeHref: 'tennis.html',
    dataModule: 'tennis',
  },
  {
    id: 'khyaali-bhoot',
    displayName: 'Khyaali Bhoot',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="khyaali-bhoot.html"]',
    handlerName: 'navigateKhyaaliBhootPage',
    ownerPath: 'src/modules/khyaali-bhoot/controller.ts',
    iconElementId: 'khyaali-bhoot-icon',
    routeHref: 'khyaali-bhoot.html',
    dataModule: 'khyaali-bhoot',
  },
  {
    id: 'food',
    displayName: 'Food',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#food-clickable-day',
    handlerName: 'showFoodModal',
    ownerPath: 'src/modules/food/controller.ts',
    iconElementId: 'food-icon',
    modalId: 'food-modal',
    dataModule: 'food',
  },
];
