export const MODULE_REGISTRY_DATA = [
  {
    id: 'todo',
    displayName: 'To do',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="todo.html"]',
    handlerName: 'navigateTodoPage',
    ownerPath: 'src/modules/todo/controller.ts',
    routeHref: 'todo.html',
    dataModule: 'todo',
  },
  {
    id: 'khyaali-bhoot',
    displayName: 'Khyaali Bhoot',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="khyaali-bhoot.html"]',
    handlerName: 'navigateKhyaaliBhootPage',
    ownerPath: 'src/modules/khyaali-bhoot/controller.ts',
    routeHref: 'khyaali-bhoot.html',
    dataModule: 'khyaali-bhoot',
  },
  {
    id: 'tennis',
    displayName: 'Tennis',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="tennis.html"]',
    handlerName: 'navigateTennisPage',
    ownerPath: 'src/modules/tennis/controller.ts',
    routeHref: 'tennis.html',
    dataModule: 'tennis',
  },
  {
    id: 'food',
    displayName: 'Food',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="food.html"]',
    handlerName: 'renderFoodView',
    ownerPath: 'src/modules/food/controller.ts',
    routeHref: 'food.html',
    dataModule: 'food',
  },
];
