export const MODULE_REGISTRY_DATA = [
  {
    id: 'todo',
    displayName: 'To do',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="todo.html"]',
    handlerName: 'navigateTodoPage',
    ownerPath: 'src/todo.tsx',
    iconElementId: 'todo-icon',
    routeHref: 'todo.html',
    dataModule: 'todo',
  },
  {
    id: 'quantum',
    displayName: 'Quantum',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="quantum.html"]',
    handlerName: 'navigateQuantumPage',
    ownerPath: 'src/pages/quantum.ts',
    iconElementId: 'quantum-icon',
    routeHref: 'quantum.html',
    dataModule: 'quantum',
  },
  {
    id: 'meditate',
    displayName: 'Meditate',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="meditate.html"]',
    handlerName: 'navigateMeditatePage',
    ownerPath: 'src/pages/meditate.ts',
    iconElementId: 'meditate-icon',
    routeHref: 'meditate.html',
    dataModule: 'meditate',
  },
  {
    id: 'money',
    displayName: 'Money',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="money.html"]',
    handlerName: 'navigateMoneyPage',
    ownerPath: 'src/pages/money.ts',
    iconElementId: 'money-icon',
    routeHref: 'money.html',
    dataModule: 'money',
  },
  {
    id: 'health',
    displayName: 'Health',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="health.html"]',
    handlerName: 'navigateHealthPage',
    ownerPath: 'src/pages/health.ts',
    iconElementId: 'health-icon',
    routeHref: 'health.html',
    dataModule: 'health',
  },
  {
    id: 'travel',
    displayName: 'Travel',
    category: 'journey',
    surface: 'page',
    entrySelector: 'a[href="travel.html"]',
    handlerName: 'navigateTravelPage',
    ownerPath: 'src/pages/travel.ts',
    iconElementId: 'travel-icon',
    routeHref: 'travel.html',
    dataModule: 'travel',
  },
  {
    id: 'world-order',
    displayName: 'World Order',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#geopolitics-clickable',
    handlerName: 'fetchAndShowWorldOrder',
    ownerPath: 'src/components/modals/worldOrderModal.ts',
    iconElementId: 'world-order-icon',
    modalId: 'geopolitics-modal',
    dataModule: 'world-order',
  },
  {
    id: 'tennis',
    displayName: 'Tennis',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#tennis-clickable',
    handlerName: 'fetchAndShowTennisMatches',
    ownerPath: 'src/components/modals/tennisModal.ts',
    iconElementId: 'tennis-icon',
    modalId: 'tennis-modal',
    dataModule: 'tennis',
  },
  {
    id: 'coffee',
    displayName: 'Coffee',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#coffee-clickable',
    handlerName: 'showCoffeeMenu',
    ownerPath: 'src/components/modals/coffeeModal.ts',
    iconElementId: 'coffee-icon',
    modalId: 'coffee-modal',
    dataModule: 'coffee',
  },
  {
    id: 'guitar',
    displayName: 'Mr. Mojo',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#guitar-clickable',
    handlerName: 'openMrMojoRising',
    ownerPath: 'src/components/modals/guitarModal.ts',
    iconElementId: 'guitar-icon',
    modalId: 'guitar-modal',
    dataModule: 'guitar',
  },
  {
    id: 'poetry',
    displayName: 'Poetry',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#poetry-clickable',
    handlerName: 'fetchAndShowPoetry',
    ownerPath: 'src/components/modals/poetryModal.ts',
    iconElementId: 'poetry-icon',
    modalId: 'poetry-modal',
    dataModule: 'poetry',
  },
  {
    id: 'french',
    displayName: 'French',
    category: 'learn',
    surface: 'page',
    entrySelector: '#french-clickable-day',
    handlerName: 'navigateToFrenchPage',
    ownerPath: 'src/apps/french-translator/main.tsx',
    iconElementId: 'french-icon',
    routeHref: 'french.html',
    dataModule: 'french',
  },
  {
    id: 'food',
    displayName: "Today's Food",
    category: 'learn',
    surface: 'modal',
    entrySelector: '#food-clickable-day',
    handlerName: 'showFoodModal',
    ownerPath: 'src/components/modals/foodModal.ts',
    iconElementId: 'food-icon',
    modalId: 'food-modal',
    dataModule: 'food',
  },
  {
    id: 'analytics',
    displayName: 'Analytics',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#analytics-clickable-day',
    handlerName: 'showAnalyticsModal',
    ownerPath: 'src/components/modals/analytics/controller.ts',
    iconElementId: 'analytics-icon',
    modalId: 'analytics-engineer-modal',
    dataModule: 'analytics',
  },
  {
    id: 'curious',
    displayName: 'Curious',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#hood-clickable-day',
    handlerName: 'showHoodModal',
    ownerPath: 'src/components/modals/hoodModal.ts',
    iconElementId: 'curious-icon',
    modalId: 'hood-modal',
    dataModule: 'curious',
  },
  {
    id: 'exercise',
    displayName: 'Exercise',
    category: 'learn',
    surface: 'modal',
    entrySelector: '#exercise-clickable-day',
    handlerName: 'showExerciseModal',
    ownerPath: 'src/components/modals/exercise/controller.ts',
    iconElementId: 'exercise-icon',
    modalId: 'exercise-modal',
    dataModule: 'exercise',
  },
];
